export const MOCK_CHANNELS = [
  {
    id: '1',
    name: 'Ekushey TV',
    category: 'News',
    nowPlaying: 'Evening News',
    logoBg: '#e8f5e9',
    logoColor: '#2e7d32',
    iconName: 'antenna',
    streamUrl: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  },
  {
    id: '2',
    name: 'BTV',
    category: 'Entertainment',
    nowPlaying: 'Bangla Drama',
    logoBg: '#fff3e0',
    logoColor: '#ef6c00',
    iconName: 'television',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '3',
    name: 'NTV',
    category: 'News',
    nowPlaying: 'Today\'s News',
    logoBg: '#e3f2fd',
    logoColor: '#1565c0',
    iconName: 'radio-tower',
    streamUrl: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  },
  {
    id: '4',
    name: 'ATN Bangla',
    category: 'Entertainment',
    nowPlaying: 'Cinema Time',
    logoBg: '#f3e5f5',
    logoColor: '#7b1fa2',
    iconName: 'antenna',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '5',
    name: 'HBO',
    category: 'Entertainment',
    nowPlaying: 'Action Blockbuster',
    logoBg: '#ffebee',
    logoColor: '#c62828',
    iconName: 'movie-roll',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '6',
    name: 'CNN',
    category: 'News',
    nowPlaying: 'Global Newsroom',
    logoBg: '#e0f7fa',
    logoColor: '#00838f',
    iconName: 'earth',
    streamUrl: 'https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8',
  },
  {
    id: '7',
    name: 'SONY Sports',
    category: 'Sports',
    nowPlaying: 'Live Cricket Match',
    logoBg: '#fce4ec',
    logoColor: '#ad1457',
    iconName: 'trophy',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '8',
    name: 'Discovery',
    category: 'Entertainment',
    nowPlaying: 'Wild Life Chronicles',
    logoBg: '#f1f8e9',
    logoColor: '#558b2f',
    iconName: 'leaf',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
];

export const MOCK_MOVIES = [
  {
    id: 'm1',
    title: 'The Voyager',
    genre: 'Drama',
    year: '2025',
    duration: '2h 18m',
    rating: '8.5',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800',
    description: 'An emotional family drama about dreams, love, and life\'s challenges. Directed by Rashed Karim. Featuring an award-winning performance by the lead cast. The story follows a young sailor who finds himself lost at sea, both literally and metaphorically.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c1', name: 'Rahul Dev', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100' },
      { id: 'c2', name: 'Moushumi', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100' },
      { id: 'c3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
      { id: 'c4', name: 'Purnima', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=100' },
    ]
  },
  {
    id: 'm2',
    title: 'Inception',
    genre: 'Sci-Fi',
    year: '2010',
    duration: '2h 28m',
    rating: '8.8',
    image: 'https://images.unsplash.com/photo-1616530940355-351fabd9524b?q=80&w=800',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: true,
    isNew: false,
    cast: [
      { id: 'c5', name: 'Shakib Khan', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100' },
      { id: 'c2', name: 'Moushumi', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100' },
    ]
  },
  {
    id: 'm3',
    title: 'Dark Knight',
    genre: 'Action',
    year: '2008',
    duration: '2h 32m',
    rating: '9.0',
    image: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: false,
    isNew: false,
    cast: [
      { id: 'c3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
      { id: 'c5', name: 'Shakib Khan', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100' },
    ]
  },
  {
    id: 'm4',
    title: 'Mystic Forest',
    genre: 'Drama',
    year: '2024',
    duration: '2h 10m',
    rating: '8.8',
    image: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=400',
    description: 'A deep emotional drama tracking the struggles of a community situated in the isolated forests of north Bengal. Secrets of the past haunt the village residents.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c1', name: 'Rahul Dev', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100' },
      { id: 'c4', name: 'Purnima', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=100' },
    ]
  },
  {
    id: 'm5',
    title: 'Stormy Night',
    genre: 'Sci-Fi',
    year: '2024',
    duration: '1h 45m',
    rating: '7.5',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=400',
    description: 'A localized weather storm triggers an anomaly in spacetime, bringing an isolated town in contact with beings from a parallel timeline.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
    ]
  },
  {
    id: 'm6',
    title: 'Golden Girl',
    genre: 'Romance',
    year: '2024',
    duration: '2h 05m',
    rating: '9.2',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400',
    description: 'An elegant romance that charts the life of a gifted painter from Pabna as she struggles to gain recognition in Dhaka while balancing her love life.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c2', name: 'Moushumi', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100' },
      { id: 'c4', name: 'Purnima', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=100' },
    ]
  },
  {
    id: 'm7',
    title: 'Path of Light',
    genre: 'Mystery',
    year: '2024',
    duration: '1h 55m',
    rating: '6.8',
    image: 'https://images.unsplash.com/photo-1505775561242-727b7fba20f0?q=80&w=400',
    description: 'A brilliant detective follows cryptic codes left behind in old temples to uncover a major art smuggling syndicate.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: true,
    isNew: true,
    cast: [
      { id: 'c1', name: 'Rahul Dev', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100' },
    ]
  },
  {
    id: 'm8',
    title: 'Rain Song',
    genre: 'Drama',
    year: '2024',
    duration: '2h 15m',
    rating: '8.1',
    image: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800',
    description: 'Musical drama charting the rise and fall of a classical baul singer in rural Bangladesh struggling to keep his ancestors\' musical traditions alive.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: true,
    isNew: true,
    cast: [
      { id: 'c3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
    ]
  },
  {
    id: 'm9',
    title: 'The Silence',
    genre: 'Thriller',
    year: '2024',
    duration: '1h 50m',
    rating: '7.9',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800',
    description: 'A tense home-invasion thriller where a deaf woman must outsmart a group of intruders using her sensory knowledge of her house.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: true,
    isNew: true,
    cast: [
      { id: 'c2', name: 'Moushumi', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100' },
    ]
  },
  {
    id: 'm10',
    title: 'Neon Dreams',
    genre: 'Action',
    year: '2024',
    duration: '2h 00m',
    rating: '8.4',
    image: 'https://images.unsplash.com/photo-1616530940355-351fabd9524b?q=80&w=800',
    description: 'Sci-fi action set in a neon-lit futuristic Dhaka. An ex-cop goes rogue to find the hacker who deleted his daughter\'s digital memories.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c5', name: 'Shakib Khan', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100' },
    ]
  },
  {
    id: 'm11',
    title: 'Last Stand',
    genre: 'War',
    year: '2024',
    duration: '2h 30m',
    rating: '9.0',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?q=80&w=800',
    description: 'A historical recount of a small infantry unit defending their outpost against overwhelming enemy forces during the liberation war.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c1', name: 'Rahul Dev', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100' },
      { id: 'c3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
    ]
  },
  {
    id: 'm12',
    title: 'Shadow Falls',
    genre: 'Horror',
    year: '2024',
    duration: '1h 40m',
    rating: '7.2',
    image: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800',
    description: 'A classic supernatural thriller surrounding a haunted house in the suburbs and a family that slowly unravels its terrifying legacy.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: true,
    isMustWatch: false,
    isNew: true,
    cast: [
      { id: 'c4', name: 'Purnima', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=100' },
    ]
  },
  {
    id: 'm13',
    title: 'Ocean Blue',
    genre: 'Nature',
    year: '2024',
    duration: '1h 30m',
    rating: '8.5',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800',
    description: 'A breathtaking documentary exploring the rich marine ecosystems of the Bay of Bengal, capturing rare footage of ocean creatures.',
    streamUrl: 'https://vjs.zencdn.net/v/oceans.mp4',
    isTrending: false,
    isMustWatch: false,
    isNew: true,
    cast: []
  }
];

export const MOCK_ACTORS = [
  { id: 'a1', name: 'Rahul Dev', image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=100' },
  { id: 'a2', name: 'Moushumi', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100' },
  { id: 'a3', name: 'Ferdous', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100' },
  { id: 'a4', name: 'Purnima', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=100' },
  { id: 'a5', name: 'Shakib Khan', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100' },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    type: 'channel_update',
    title: 'New Channels Added',
    description: 'Sony LIV, Zee Bangla and 3 more new HD channels have been added to your package. Explore now!',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    type: 'app_update',
    title: 'App Update Available (v2.1.0)',
    description: 'A new version of PPLEX is available! Enjoy faster streaming, PiP mode improvements and bug fixes.',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    type: 'sports',
    title: 'Live Sports Alert',
    description: 'Real Madrid vs Barcelona kick-off starts in 30 minutes. Watch live on SONY Sports HD.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    type: 'movie',
    title: 'New Movie: Mystic Forest',
    description: 'A new emotional drama is now streaming on PPLEX. Watch it now before everyone else!',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    type: 'promo',
    title: 'Subscription Ending Soon',
    description: 'Your premium plan expires in 3 days. Renew now and get 20% off on all packages.',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    type: 'channel_update',
    title: 'Channel Quality Upgraded',
    description: 'BTV, NTV and ATN Bangla are now available in Full HD. Enjoy a better viewing experience.',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    type: 'alert',
    title: 'Scheduled Maintenance',
    description: 'PPLEX will undergo brief maintenance tonight from 2:00 AM – 3:00 AM. Services may be interrupted.',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    type: 'system',
    title: 'Security Update',
    description: 'Please update your account password to keep your account secure.',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const USER_PROFILE = {
  name: 'Rahim Mia',
  email: 'rahim.mia@pplex.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200',
  activePackage: 'Silver Package',
  expiresOn: 'Jun 12, 2026',
  remainingDays: 18,
  totalDays: 30,
  helpline: '01700-000000',
};
